### ISSUE TITLE
OCP 4.11 may have different channel for local storage operator

### ISSUE THREAD

**Issue by kanekoh** [kanekoh/openshift-env-helper#7]
Trying installation for 4.11 on KVM and got failed following error message.
```
.No resources found in openshift-local-storage namespace.
```

Currently script applied following subscription however, channel name could be 'stable' for the latest OCP 4.11
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: "${OC_VERSION}"
  installPlanApproval: Automatic
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
```
